export const nameRegex =
  /^([A-Za-zñÑáéíóúZÁÉÍÓÚ ]{2,30})\s?([A-Za-zñÑáéíóúZÁÉÍÓÚ ]+)/g;

export const states = [
  {
    state: "Amazonas",
    cities: [
      "El Encanto",
      "La Chorrera",
      "La Pedrera",
      "La Victoria",
      "Leticia",
      "Miriti - Paraná",
      "Puerto Alegría",
      "Puerto Arica",
      "Puerto Nariño",
      "Puerto Santander",
      "Tarapacá",
    ],
  },
  {
    state: "Antioquia",
    cities: [
      "Abejorral",
      "Abriaquí",
      "Alejandría",
      "Altamira",
      "Amagá",
      "Amalfi",
      "Andes",
      "Angelópolis",
      "Angostura",
      "Anorí",
      "Anzá",
      "Apartadó",
      "Arboletes",
      "Argelia",
      "Armenia",
      "Barbosa",
      "Bello",
      "Belmira",
      "Betania",
      "Betulia",
      "Briceño",
      "Buriticá",
      "Cáceres",
      "Caicedo",
      "Caldas",
      "Campamento",
      "Cañasgordas",
      "Caracolí",
      "Caramanta",
      "Carepa",
      "Carolina",
      "Caucasia",
      "Chigorodó",
      "Cisneros",
      "Ciudad Bolívar",
      "Cocorná",
      "Concepción",
      "Concordia",
      "Copacabana",
      "Dabeiba",
      "Donmatías",
      "Ebéjico",
      "El Bagre",
      "El Carmen De Viboral",
      "El Santuario",
      "Entrerríos",
      "Envigado",
      "Fredonia",
      "Frontino",
      "Giraldo",
      "Girardota",
      "Gómez Plata",
      "Granada",
      "Guadalupe",
      "Guarne",
      "Guatapé",
      "Heliconia",
      "Hispania",
      "Itagüí",
      "Ituango",
      "Jardín",
      "Jericó",
      "La Ceja",
      "La Estrella",
      "La Pintada",
      "La Unión",
      "Liborina",
      "Maceo",
      "Marinilla",
      "Medellín",
      "Montebello",
      "Murindó",
      "Mutatá",
      "Nariño",
      "Nechí",
      "Necoclí",
      "Olaya",
      "Peñol",
      "Peque",
      "Pueblorrico",
      "Puerto Berrío",
      "Puerto Nare",
      "Puerto Triunfo",
      "Remedios",
      "Retiro",
      "Rionegro",
      "Sabanalarga",
      "Sabaneta",
      "Salgar",
      "San Andrés De Cuerquía",
      "San Carlos",
      "San Cristóbal",
      "San Francisco",
      "San Jerónimo",
      "San José De La Montaña",
      "San Juan De Urabá",
      "San Luis",
      "San Pedro De Los Milagros",
      "San Pedro De Urabá",
      "San Rafael",
      "San Roque",
      "San Vicente Ferrer",
      "Santa Bárbara",
      "Santa Fe De Antioquia",
      "Santa Rosa De Osos",
      "Santo Domingo",
      "Segovia",
      "Sonsón",
      "Sopetrán",
      "Támesis",
      "Tarazá",
      "Tarso",
      "Titiribí",
      "Toledo",
      "Turbo",
      "Uramita",
      "Urrao",
      "Valdivia",
      "Valparaíso",
      "Vegachí",
      "Venecia",
      "Vigía Del Fuerte",
      "Yalí",
      "Yarumal",
      "Yolombó",
      "Yondó",
      "Zaragoza",
    ],
  },
  {
    state: "Arauca",
    cities: [
      "Arauca",
      "Arauquita",
      "Cravo Norte",
      "Fortul",
      "Puerto Rondón",
      "Saravena",
      "Tame",
    ],
  },
  {
    state: "Atlántico",
    cities: [
      "Baranoa",
      "Barranquilla",
      "Campo De La Cruz",
      "Candelaria",
      "Galapa",
      "Juan De Acosta",
      "Luruaco",
      "Malambo",
      "Manatí",
      "Palmar De Varela",
      "Piojó",
      "Polonuevo",
      "Ponedera",
      "Puerto Colombia",
      "Repelón",
      "Sabanagrande",
      "Sabanalarga",
      "Santa Lucía",
      "Santo Tomás",
      "Soledad",
      "Suan",
      "Tubará",
      "Usiacurí",
    ],
  },
  { state: "Bogotá", cities: ["Bogotá, D.C."] },
  {
    state: "Bolívar",
    cities: [
      "Achí",
      "Altos Del Rosario",
      "Arenal",
      "Arjona",
      "Arroyohondo",
      "Barranco De Loba",
      "Calamar",
      "Cantagallo",
      "Cartagena De Indias",
      "Cicuco",
      "Clemencia",
      "Córdoba",
      "El Carmen De Bolívar",
      "El Guamo",
      "El Peñón",
      "Hatillo De Loba",
      "Magangué",
      "Mahates",
      "Margarita",
      "María La Baja",
      "Mompós",
      "Montecristo",
      "Morales",
      "Norosí",
      "Pinillos",
      "Regidor",
      "Río Viejo",
      "San Cristóbal",
      "San Estanislao",
      "San Fernando",
      "San Jacinto",
      "San Jacinto Del Cauca",
      "San Juan Nepomuceno",
      "San Martín De Loba",
      "San Pablo",
      "Santa Catalina",
      "Santa Rosa",
      "Santa Rosa Del Sur",
      "Simití",
      "Soplaviento",
      "Talaigua Nuevo",
      "Tiquisio",
      "Turbaco",
      "Turbaná",
      "Villanueva",
      "Zambrano",
    ],
  },
  {
    state: "Boyacá",
    cities: [
      "Almeida",
      "Aquitania",
      "Arcabuco",
      "Belén",
      "Berbeo",
      "Betéitiva",
      "Boavita",
      "Boyacá",
      "Briceño",
      "Buenavista",
      "Busbanzá",
      "Caldas",
      "Campohermoso",
      "Cerinza",
      "Chinavita",
      "Chiquinquirá",
      "Chíquiza",
      "Chiscas",
      "Chita",
      "Chitaraque",
      "Chivatá",
      "Chivor",
      "Ciénega",
      "Cómbita",
      "Coper",
      "Corrales",
      "Covarachía",
      "Cubará",
      "Cucaita",
      "Cuítiva",
      "Duitama",
      "El Cocuy",
      "El Espino",
      "Firavitoba",
      "Floresta",
      "Gachantivá",
      "Gámeza",
      "Garagoa",
      "Guacamayas",
      "Guateque",
      "Guayatá",
      "Güicán",
      "Iza",
      "Jenesano",
      "Jericó",
      "La Capilla",
      "La Uvita",
      "La Victoria",
      "Labranzagrande",
      "Macanal",
      "Maripí",
      "Miraflores",
      "Mongua",
      "Monguí",
      "Moniquirá",
      "Motavita",
      "Muzo",
      "Nobsa",
      "Nuevo Colón",
      "Oicatá",
      "Otanche",
      "Pachavita",
      "Páez",
      "Paipa",
      "Pajarito",
      "Panqueba",
      "Pauna",
      "Paya",
      "Paz De Río",
      "Pesca",
      "Pisba",
      "Puerto Boyacá",
      "Quípama",
      "Ramiriquí",
      "Ráquira",
      "Rondón",
      "Saboyá",
      "Sáchica",
      "Samacá",
      "San Eduardo",
      "San José De Pare",
      "San Luis De Gaceno",
      "San Mateo",
      "San Miguel De Sema",
      "San Pablo De Borbur",
      "Santa María",
      "Santa Rosa De Viterbo",
      "Santa Sofía",
      "Santana",
      "Sativanorte",
      "Sativasur",
      "Siachoque",
      "Soatá",
      "Socha",
      "Socotá",
      "Sogamoso",
      "Somondoco",
      "Sora",
      "Soracá",
      "Sotaquirá",
      "Susacón",
      "Sutamarchán",
      "Sutatenza",
      "Tasco",
      "Tenza",
      "Tibaná",
      "Tibasosa",
      "Tinjacá",
      "Tipacoque",
      "Toca",
      "Togüí",
      "Tópaga",
      "Tota",
      "Tunja",
      "Tununguá",
      "Turmequé",
      "Tuta",
      "Tutazá",
      "Úmbita",
      "Ventaquemada",
      "Villa De Leyva",
      "Viracachá",
      "Zetaquira",
    ],
  },
  {
    state: "Caldas",
    cities: [
      "Aguadas",
      "Anserma",
      "Aranzazu",
      "Arauca",
      "Arboleda",
      "Belalcázar",
      "Bolivia",
      "Chinchiná",
      "Filadelfia",
      "Florencia",
      "La Dorada",
      "La Merced",
      "Manizales",
      "Manzanares",
      "Marmato",
      "Marquetalia",
      "Marulanda",
      "Neira",
      "Norcasia",
      "Pácora",
      "Palestina",
      "Pensilvania",
      "Riosucio",
      "Risaralda",
      "Salamina",
      "Samaná",
      "San Felix",
      "San José",
      "San José De Risaralda",
      "Supía",
      "Victoria",
      "Villamaría",
      "Viterbo",
    ],
  },
  {
    state: "Caquetá",
    cities: [
      "Albania",
      "Belén De Los Andaquíes",
      "Cartagena Del Chairá",
      "Curillo",
      "El Doncello",
      "El Paujíl",
      "Florencia",
      "La Montañita",
      "Milán",
      "Morelia",
      "Puerto Rico",
      "San José Del Fragua",
      "San Vicente Del Caguán",
      "Solano",
      "Solita",
      "Valparaíso",
    ],
  },
  {
    state: "Casanare",
    cities: [
      "Aguazul",
      "Chámeza",
      "Hato Corozal",
      "La Salina",
      "Maní",
      "Monterrey",
      "Nunchía",
      "Orocué",
      "Paz De Ariporo",
      "Pore",
      "Recetor",
      "Sabanalarga",
      "Sácama",
      "San Luis De Palenque",
      "Támara",
      "Tauramena",
      "Trinidad",
      "Villanueva",
      "Yopal",
    ],
  },
  {
    state: "Cauca",
    cities: [
      "Almaguer",
      "Argelia",
      "Balboa",
      "Bolívar",
      "Buenos Aires",
      "Cajibío",
      "Caldono",
      "Caloto",
      "Corinto",
      "El Tambo",
      "Florencia",
      "Guachené",
      "Guapí",
      "Inzá",
      "Jambaló",
      "La Sierra",
      "La Vega",
      "López De Micay",
      "Mercaderes",
      "Miranda",
      "Morales",
      "Padilla",
      "Páez",
      "Patía",
      "Piamonte",
      "Piendamó",
      "Popayán",
      "Puerto Tejada",
      "Puracé",
      "Rosas",
      "San Sebastián",
      "Santa Rosa",
      "Santander De Quilichao",
      "Silvia",
      "Sotará",
      "Suárez",
      "Sucre",
      "Timbío",
      "Timbiquí",
      "Toribío",
      "Totoró",
      "Villa Rica",
    ],
  },
  {
    state: "Cesar",
    cities: [
      "Aguachica",
      "Agustín Codazzi",
      "Astrea",
      "Becerril",
      "Bosconia",
      "Chimichagua",
      "Chiriguaná",
      "Curumaní",
      "El Copey",
      "El Paso",
      "Gamarra",
      "González",
      "La Gloria",
      "La Jagua De Ibirico",
      "La Paz",
      "Manaure Balcón Del Cesar",
      "Pailitas",
      "Pelaya",
      "Pueblo Bello",
      "Río De Oro",
      "San Alberto",
      "San Diego",
      "San Martín",
      "Tamalameque",
      "Valledupar",
    ],
  },
  {
    state: "Chocó",
    cities: [
      "Acandí",
      "Alto Baudó",
      "Atrato",
      "Bagadó",
      "Bahía Solano",
      "Bajo Baudó",
      "Bajo San Juan",
      "Belén De Bajirá",
      "Bojayá",
      "Carmen Del Darién",
      "Cértegui",
      "Condoto",
      "El Cantón Del San Pablo",
      "El Carmen De Atrato",
      "El Litoral Del San Juan",
      "Istmina",
      "Juradó",
      "Lloró",
      "Medio Atrato",
      "Medio Baudó",
      "Medio San Juan",
      "Nóvita",
      "Nuquí",
      "Quibdó",
      "Río Iró",
      "Río Quito",
      "Riosucio",
      "San José Del Palmar",
      "Sipí",
      "Tadó",
      "Unguía",
      "Unión Panamericana",
    ],
  },
  {
    state: "Córdoba",
    cities: [
      "Ayapel",
      "Buenavista",
      "Canalete",
      "Cereté",
      "Chimá",
      "Chinú",
      "Ciénaga De Oro",
      "Cotorra",
      "La Apartada",
      "Lorica",
      "Los Córdobas",
      "Momil",
      "Montelíbano",
      "Montería",
      "Moñitos",
      "Planeta Rica",
      "Pueblo Nuevo",
      "Puerto Escondido",
      "Puerto Libertador",
      "Purísima",
      "Sahagún",
      "San Andrés De Sotavento",
      "San Antero",
      "San Bernardo Del Viento",
      "San Carlos",
      "San José De Uré",
      "San Pelayo",
      "Tierralta",
      "Tuchín",
      "Valencia",
    ],
  },
  {
    state: "Cundinamarca",
    cities: [
      "Agua De Dios",
      "Albán",
      "Anapoima",
      "Anolaima",
      "Apulo",
      "Arbeláez",
      "Beltrán",
      "Bituima",
      "Bojacá",
      "Cabrera",
      "Cachipay",
      "Cajicá",
      "Caparrapí",
      "Cáqueza",
      "Carmen De Carupa",
      "Chaguaní",
      "Chía",
      "Chipaque",
      "Choachí",
      "Chocontá",
      "Cogua",
      "Cota",
      "Cucunubá",
      "El Colegio",
      "El Peñón",
      "El Rosal",
      "Facatativá",
      "Fómeque",
      "Fosca",
      "Funza",
      "Fúquene",
      "Fusagasugá",
      "Gachalá",
      "Gachancipá",
      "Gachetá",
      "Gama",
      "Girardot",
      "Granada",
      "Guachetá",
      "Guaduas",
      "Guasca",
      "Guataquí",
      "Guatavita",
      "Guayabal De Síquima",
      "Guayabetal",
      "Gutiérrez",
      "Jerusalén",
      "Junín",
      "La Calera",
      "La Mesa",
      "La Palma",
      "La Peña",
      "La Vega",
      "Lenguazaque",
      "Machetá",
      "Madrid",
      "Manta",
      "Medina",
      "Mosquera",
      "Nariño",
      "Nemocón",
      "Nilo",
      "Nimaima",
      "Nocaima",
      "Pacho",
      "Paime",
      "Pandi",
      "Paratebueno",
      "Pasca",
      "Puerto Salgar",
      "Pulí",
      "Quebradanegra",
      "Quetame",
      "Quipile",
      "Ricaurte",
      "San Antonio Del Tequendama",
      "San Bernardo",
      "San Cayetano",
      "San Francisco",
      "San Juan De Rioseco",
      "Sasaima",
      "Sesquilé",
      "Sibaté",
      "Silvania",
      "Simijaca",
      "Soacha",
      "Sopó",
      "Subachoque",
      "Suesca",
      "Supatá",
      "Susa",
      "Sutatausa",
      "Tabio",
      "Tausa",
      "Tena",
      "Tenjo",
      "Tibacuy",
      "Tibirita",
      "Tocaima",
      "Tocancipá",
      "Topaipí",
      "Ubalá",
      "Ubaque",
      "Une",
      "Útica",
      "Venecia",
      "Vergara",
      "Vianí",
      "Villa De San Diego De Ubaté",
      "Villagómez",
      "Villapinzón",
      "Villeta",
      "Viotá",
      "Yacopí",
      "Zipacón",
      "Zipaquirá",
    ],
  },
  {
    state: "Guainía",
    cities: [
      "Barranco Minas",
      "Cacahual",
      "Inírida",
      "La Guadalupe",
      "Mapiripana",
      "Morichal",
      "Pana Pana",
      "Puerto Colombia",
      "San Felipe",
    ],
  },
  {
    state: "Guaviare",
    cities: [
      "Calamar",
      "El Retorno",
      "Miraflores",
      "Morichal",
      "San José Del Guaviare",
    ],
  },
  {
    state: "Huila",
    cities: [
      "Acevedo",
      "Agrado",
      "Aipe",
      "Algeciras",
      "Altamira",
      "Baraya",
      "Campoalegre",
      "Colombia",
      "Elías",
      "Garzón",
      "Gigante",
      "Guadalupe",
      "Hobo",
      "Íquira",
      "Isnos",
      "La Argentina",
      "La Plata",
      "Nátaga",
      "Neiva",
      "Oporapa",
      "Paicol",
      "Palermo",
      "Palestina",
      "Pital",
      "Pitalito",
      "Rivera",
      "Saladoblanco",
      "San Agustín",
      "Santa María",
      "Suaza",
      "Tarqui",
      "Tello",
      "Teruel",
      "Tesalia",
      "Timaná",
      "Villavieja",
      "Yaguará",
    ],
  },
  {
    state: "La Guajira",
    cities: [
      "Albania",
      "Barrancas",
      "Dibulla",
      "Distracción",
      "El Molino",
      "Fonseca",
      "Hatonuevo",
      "La Jagua Del Pilar",
      "Maicao",
      "Manaure",
      "Riohacha",
      "San Juan Del Cesar",
      "Uribia",
      "Urumita",
      "Villanueva",
    ],
  },
  {
    state: "Magdalena",
    cities: [
      "Algarrobo",
      "Aracataca",
      "Ariguaní",
      "Cerro De San Antonio",
      "Chivolo",
      "Ciénaga",
      "Concordia",
      "El Banco",
      "El Piñón",
      "El Retén",
      "Fundación",
      "Guamal",
      "Nueva Granada",
      "Pedraza",
      "Pijiño Del Carmen",
      "Pivijay",
      "Plato",
      "Puebloviejo",
      "Remolino",
      "Sabanas De San Ángel",
      "Salamina",
      "San Sebastián De Buenavista",
      "San Zenón",
      "Santa Ana",
      "Santa Bárbara De Pinto",
      "Santa Marta",
      "Sitionuevo",
      "Tenerife",
      "Zapayán",
      "Zona Bananera",
    ],
  },
  {
    state: "Meta",
    cities: [
      "Acacías",
      "Barranca De Upía",
      "Cabuyaro",
      "Castilla La Nueva",
      "Cumaral",
      "El Calvario",
      "El Castillo",
      "El Dorado",
      "Fuente De Oro",
      "Granada",
      "Guamal",
      "La Macarena",
      "Lejanías",
      "Mapiripán",
      "Mesetas",
      "Puerto Concordia",
      "Puerto Gaitán",
      "Puerto Lleras",
      "Puerto López",
      "Puerto Rico",
      "Restrepo",
      "San Carlos De Guaroa",
      "San Juan De Arama",
      "San Juanito",
      "San Luis De Cubarral",
      "San Martín",
      "Uribe",
      "Villavicencio",
      "Vistahermosa",
    ],
  },
  {
    state: "Nariño",
    cities: [
      "Albán",
      "Aldana",
      "Ancuyá",
      "Arboleda",
      "Barbacoas",
      "Belén",
      "Buesaco",
      "Chachagüí",
      "Colón",
      "Consacá",
      "Contadero",
      "Córdoba",
      "Cuaspúd",
      "Cumbal",
      "Cumbitara",
      "El Charco",
      "El Peñol",
      "El Rosario",
      "El Tablón De Gómez",
      "El Tambo",
      "Francisco Pizarro",
      "Funes",
      "Guachucal",
      "Guaitarilla",
      "Gualmatán",
      "Iles",
      "Imués",
      "Ipiales",
      "La Cruz",
      "La Florida",
      "La Llanada",
      "La Tola",
      "La Unión",
      "Leiva",
      "Linares",
      "Los Andes",
      "Magüí",
      "Mallama",
      "Mosquera",
      "Nariño",
      "Olaya Herrera",
      "Ospina",
      "Pasto",
      "Policarpa",
      "Potosí",
      "Providencia",
      "Puerres",
      "Pupiales",
      "Ricaurte",
      "Roberto Payán",
      "Samaniego",
      "San Andrés De Tumaco",
      "San Bernardo",
      "San Lorenzo",
      "San Pablo",
      "San Pedro De Cartago",
      "Sandoná",
      "Santa Bárbara",
      "Santacruz",
      "Sapuyes",
      "Taminango",
      "Tangua",
      "Túquerres",
      "Yacuanquer",
    ],
  },
  {
    state: "Norte De Santander",
    cities: [
      "Ábrego",
      "Arboledas",
      "Bochalema",
      "Bucarasica",
      "Cáchira",
      "Cácota",
      "Chinácota",
      "Chitagá",
      "Convención",
      "Cúcuta",
      "Cucutilla",
      "Durania",
      "El Carmen",
      "El Tarra",
      "El Zulia",
      "Gramalote",
      "Hacarí",
      "Herrán",
      "La Esperanza",
      "La Playa",
      "Labateca",
      "Los Patios",
      "Lourdes",
      "Mutiscua",
      "Ocaña",
      "Pamplona",
      "Pamplonita",
      "Puerto Santander",
      "Ragonvalia",
      "Salazar",
      "San Calixto",
      "San Cayetano",
      "Santiago",
      "Sardinata",
      "Silos",
      "Teorama",
      "Tibú",
      "Toledo",
      "Villa Caro",
      "Villa Del Rosario",
    ],
  },
  {
    state: "Putumayo",
    cities: [
      "Colón",
      "Mocoa",
      "Orito",
      "Puerto Asís",
      "Puerto Caicedo",
      "Puerto Guzmán",
      "Puerto Leguízamo",
      "San Francisco",
      "San Miguel",
      "Santiago",
      "Sibundoy",
      "Valle Del Guamuez",
      "Villagarzón",
    ],
  },
  {
    state: "Quindio",
    cities: [
      "Armenia",
      "Buenavista",
      "Calarcá",
      "Circasia",
      "Córdoba",
      "Filandia",
      "Génova",
      "La Tebaida",
      "Montenegro",
      "Pijao",
      "Quimbaya",
      "Salento",
    ],
  },
  {
    state: "Risaralda",
    cities: [
      "Apía",
      "Balboa",
      "Belén De Umbría",
      "Dosquebradas",
      "Guática",
      "La Celia",
      "La Virginia",
      "Marsella",
      "Mistrató",
      "Pereira",
      "Pueblo Rico",
      "Quinchía",
      "Santa Rosa De Cabal",
      "Santuario",
    ],
  },
  {
    state: "Santander",
    cities: [
      "Aguada",
      "Albania",
      "Aratoca",
      "Barbosa",
      "Barichara",
      "Barrancabermeja",
      "Betulia",
      "Bolívar",
      "Bucaramanga",
      "Cabrera",
      "California",
      "Capitanejo",
      "Carcasí",
      "Cepitá",
      "Cerrito",
      "Charalá",
      "Charta",
      "Chima",
      "Chipatá",
      "Cimitarra",
      "Concepción",
      "Confines",
      "Contratación",
      "Coromoro",
      "Curití",
      "El Carmen De Chucurí",
      "El Guacamayo",
      "El Peñón",
      "El Playón",
      "Encino",
      "Enciso",
      "Florián",
      "Floridablanca",
      "Galán",
      "Gámbita",
      "Girón",
      "Guaca",
      "Guadalupe",
      "Guapotá",
      "Guavatá",
      "Güepsa",
      "Hato",
      "Jesús María",
      "Jordán",
      "La Belleza",
      "La Paz",
      "Landázuri",
      "Lebrija",
      "Los Santos",
      "Macaravita",
      "Málaga",
      "Matanza",
      "Mogotes",
      "Molagavita",
      "Ocamonte",
      "Oiba",
      "Onzaga",
      "Palmar",
      "Palmas Del Socorro",
      "Páramo",
      "Piedecuesta",
      "Pinchote",
      "Puente Nacional",
      "Puerto Parra",
      "Puerto Wilches",
      "Rionegro",
      "Sabana De Torres",
      "San Andrés",
      "San Benito",
      "San Gil",
      "San Joaquín",
      "San José De Miranda",
      "San Miguel",
      "San Vicente De Chucurí",
      "Santa Bárbara",
      "Santa Helena Del Opón",
      "Simacota",
      "Socorro",
      "Suaita",
      "Sucre",
      "Suratá",
      "Tona",
      "Valle De San José",
      "Vélez",
      "Vetas",
      "Villanueva",
      "Zapatoca",
    ],
  },
  { state: "San Andrés", cities: ["Providencia", "San Andrés"] },
  {
    state: "Sucre",
    cities: [
      "Buenavista",
      "Caimito",
      "Chalán",
      "Colosó",
      "Corozal",
      "Coveñas",
      "El Roble",
      "Galeras",
      "Guaranda",
      "La Unión",
      "Los Palmitos",
      "Majagual",
      "Morroa",
      "Ovejas",
      "Palmito",
      "Sampués",
      "San Benito Abad",
      "San Juan De Betulia",
      "San Luis De Sincé",
      "San Marcos",
      "San Onofre",
      "San Pedro",
      "Santiago De Tolú",
      "Sincelejo",
      "Sucre",
      "Tolú Viejo",
    ],
  },
  {
    state: "Tolima",
    cities: [
      "Alpujarra",
      "Alvarado",
      "Ambalema",
      "Anzoátegui",
      "Armero Guayabal",
      "Ataco",
      "Cajamarca",
      "Carmen De Apicalá",
      "Casabianca",
      "Chaparral",
      "Coello",
      "Coyaima",
      "Cunday",
      "Dolores",
      "Espinal",
      "Falan",
      "Flandes",
      "Fresno",
      "Guamo",
      "Herrera",
      "Herveo",
      "Honda",
      "Ibagué",
      "Icononzo",
      "Lérida",
      "Líbano",
      "Melgar",
      "Murillo",
      "Natagaima",
      "Ortega",
      "Palocabildo",
      "Piedras",
      "Planadas",
      "Prado",
      "Purificación",
      "Rioblanco",
      "Roncesvalles",
      "Rovira",
      "Saldaña",
      "San Antonio",
      "San Luis",
      "San Sebastián De Mariquita",
      "Santa Isabel",
      "Santiago Pérez",
      "Suárez",
      "Valle De San Juan",
      "Venadillo",
      "Villahermosa",
      "Villarrica",
    ],
  },
  {
    state: "Valle Del Cauca",
    cities: [
      "Alcalá",
      "Andalucía",
      "Ansermanuevo",
      "Argelia",
      "Bolívar",
      "Buenaventura",
      "Bugalagrande",
      "Caicedonia",
      "Cali",
      "Calima",
      "Candelaria",
      "Cartago",
      "Dagua",
      "El Águila",
      "El Cairo",
      "El Cerrito",
      "El Dovio",
      "Florida",
      "Ginebra",
      "Guacarí",
      "Guadalajara De Buga",
      "Jamundí",
      "La Cumbre",
      "La Unión",
      "La Victoria",
      "Obando",
      "Palmira",
      "Pradera",
      "Restrepo",
      "Riofrío",
      "Roldanillo",
      "San Pedro",
      "Sevilla",
      "Toro",
      "Trujillo",
      "Tuluá",
      "Ulloa",
      "Versalles",
      "Vijes",
      "Yotoco",
      "Yumbo",
      "Zarzal",
    ],
  },
  {
    state: "Vaupés",
    cities: [
      "Carurú",
      "Mitú",
      "Pacoa",
      "Papunaua",
      "Taraira",
      "Yavaraté",
      "Cumaribo",
      "La Primavera",
      "Puerto Carreño",
      "San José De Ocuné",
      "Santa Rita",
      "Santa Rosalía",
    ],
  },
];

export const translations = {
  name: "Nombre",
  email: "Correo",
  document: "Documento",
  phone: "Teléfono",
  city: "Ciudad",
  state: "Departamento",
  farm: "Finca/Veredad",
  code: "Código",
  producer: "Productor",
  altitude: "Altitud (m.s.n.m.)",
  variety: "Variedad",
  leader: "Catador líder",
  samples: "Número de muestras",
  testers: "Número de catadores",
  startAt: "Fecha",
};

export const categories = {
  smell: "Aroma",
  acidity: "Acidez",
  bitterness: "Amargor",
  astringency: "Astringencia",
  defects: "Defectos",
  flavor: "Sabor",
  aftertaste: "Pos Gusto",
};
